name = "iconophor"
type = 'javascript'

account_id = '0856d2d5591e4db6f1876ef8477f6a4e'
route = ''
zone_id = ''
usage_model = ''
workers_dev = true

[build]
command = "npm run build"

[build.upload]
format = "service-worker"
